### ISSUE TITLE
Electronic lock with open button and close button

### ISSUE THREAD

**Issue by Yamakatsu63** [Yamakatsu63/Verilog2go-TDD-example#1]
- [x] Set lock to 0 when key is 1 #7
- [x] Set lock to 1 when close is 1. #9 
- [x] Operate lock when clk starts up. #10
