### ISSUE TITLE
Of the open buttons from 0 to 9, press the correct button to unlock.

### ISSUE THREAD

**Issue by Yamakatsu63** [Yamakatsu63/Verilog2go-TDD-example#3]
- [x] Make the input 10 bits #17 
- [x] If the 7th bit is 1 at the start of clk, 7 is saved in the 4-bit register. #18
- [x] Set lock to 0 when the 4-bit register is 7. #19
- [x] If close is 1 at the start of clk, initialize the register. #20
