### ISSUE TITLE
Press the unlock buttons 0-9 twice in the correct order to unlock.

### ISSUE THREAD

**Issue by Yamakatsu63** [Yamakatsu63/Verilog2go-TDD-example#4]
- [x] Make the register an array of size 2 #25
- [x] Shift and hold input to register #26
- [x] Set lock to 0 when it becomes 1 in the order of the 7th bit and the 3rd bit. #27
- [x] If close is 1 at the start of clk, initialize the register. #28
