### ISSUE TITLE
Unlock by pressing the unlock buttons 0-9 four times in the correct order

### ISSUE THREAD

**Issue by Yamakatsu63** [Yamakatsu63/Verilog2go-TDD-example#6]
- [x] Make the register an array of size 4 #36
- [x] Shift and hold the input to a 4-bit register #39
- [x] Set lock to 0 when input in the order of 5,9,6,3 #37
- [x] If close is 1 at the start of clk, initialize the 4-bit register. #40
- [x] If reset is 1 at the start of clk, initialize the 4-bit register. #41
